config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :lotteries

  get 'get_lotteries', to: 'lotteries#get_data', :as => 'get_lottery'

  resources :items
  resources :items_imports, only: [:new, :create]
  resources :archives, only: [:index, :new, :create, :destroy]


  devise_for :users

  get 'results'                     => 'results#index',   :as => 'results'
  get 'results/:patient_id'         => 'results#show',    :as => 'results_show'
  get 'results/:patient_id/export'  => 'results#export',  :as => 'results_export'

  resources :forms, only: [ :new, :create, :index, :show] do
    resources :questions, only: [:index, :show] do
      resources :answers
    end
  end

  namespace :api do
    namespace :v1 do
      get 'lotteries/:phone_number', to: 'api#lotteries_by_phone_number', :as => 'lotteries_by_phone_number'
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  # validations
  validates_presence_of :user_id, :form_id, :question_id, :sub_question_id, :form_name, :question_text, :value

  def self.get_answers(user_id)
    Answer.where(user_id: user_id)
  end

  def self.get_answers_for_export(user_id)
    Answer.select("form_name, question_text, value").where(user_id: user_id)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |form|
        csv << form.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  mount_uploader :attachment, DocumentUploader
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
  include ActiveModel::Model
  require 'roo'

  attr_accessor :file

  def initialize(attributes={})
    attributes.each { |title, value| send("#{title}=", value) } unless attributes.nil?
  end

  def persisted?
    false
  end

  def open_spreadsheet
    case File.extname(file.path)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.path}"
    end
  end

  def load_imported_forms
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(5)
    (6..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      form = Form.find_by_id(row["id"]) || Form.new
      form.attributes = row.to_hash
      form
    end
  end

  def imported_forms
    @imported_forms ||= load_imported_forms
  end

  def save
    if imported_forms.map(&:valid?).all?
      imported_forms.each(&:save!)
      true
    else
      imported_forms.each_with_index do |form, index|
        form.errors.full_messages.each do |msg|
          errors.add :base, "Row #{index + 6}: #{msg}"
        end
      end
      false
    end
  end
  # model association
  # has_many :questions, dependent: :destroy

  # validations
  # validates_presence_of :title, :description
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :phone_number
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :attachment
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(attachment.original_filename)
      when ".xlsx" then Roo::Excelx.new('public/' + DocumentUploader.store_dir + '/' + attachment.original_filename)
      else raise "Unknown file type: #{attachment.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(2)
      (3..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by(phone_number: row["phone_number"], price_info: row["price_info"]) || Item.new
        if item.price_info != nil && row["price_info"].to_i >= 100000
          lottery_count = row["price_info"].to_i/100000
          string_arr = Lottery.pluck(:lottery_number)
          l_number_arr = string_arr.map(&:to_i)
          for lottery in 1..lottery_count
            lottery = Lottery.new do |l|
              l.phone_number = row["phone_number"]
              random_pick = ([*1..99999] - l_number_arr).sample
              l_number_arr.push(random_pick)              
              random_pick.to_s.rjust(5, "0")
              l.lottery_number = random_pick
            end
            lottery.save!
          end
        end
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/models/lottery.rb
class Lottery < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  # model association
  belongs_to :form

  # validations
  validates_presence_of :form_id, :sub_question_id, :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # role_id 0 = doctor, 1 = patients (default)
  def self.get_patients
    User.where(role_id: 1)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results/patients
  def index
    @patients = User.get_patients
  end
  
  # GET /results/:patient_id
  def show
    @answers = Answer.get_answers(params[:patient_id])
  end

  def export
    # download csv or xls
    @answers = Answer.get_answers_for_export(params[:patient_id])

    respond_to do |format|
      format.html
      format.csv { send_data @answers.to_csv }
      format.xls { send_data @answers.to_csv(col_sep: "\t") }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/icon_helper.rb
module IconHelper
  def icon_svg(path, html_options = {})
    content_tag :i, html_options.merge(class: "#{html_options[:class]} d-inline-block") do
      inline_svg path, class: "d-inline-block", width: "100%", height: "100%", preserve_aspect_ratio: "xMaxYMax meet"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def is_active?(link_path, return_class = "active")
    current_page?(link_path) ? return_class : nil
  end

  def markdown(source)
    options = {
      input: 'GFM',
      syntax_highlighter: :rouge,
      syntax_highlighter_opts: {
        css_class: 'highlight p-4 mb-0'
      }
    }
    Kramdown::Document.new(source, options).to_html.html_safe
  end

  def render_source(input, language = :erb, filename = nil)
    capture do
      concat content_tag(:p, "📂 #{filename}", class: "bg-light border small font-weight-bold px-4 py-2 mb-0 mt-4") if filename
      concat markdown("```#{language.to_s}\n#{input}```")
    end
  end
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/results/_form_wrapper_mappings.html.erb
<%= simple_form_for @form, url: forms_vertical_path,
  wrapper_mappings: {
    check_boxes:    :vertical_collection,
    radio_buttons:  :vertical_collection,
    file:           :custom_file,
    boolean:        :custom_boolean_switch
  } do |f| %>
  <%= f.error_notification %>

  <%= f.input :email %>

  <%= f.input :password %>

  <%= f.input :avatar, as: :file %>

  <%= f.input :pill, as: :radio_buttons,
    collection: ['Red', 'Blue'] %>

  <%= f.input :choices, as: :check_boxes,
    collection: [
      "Option one is this and that—be sure to include why it's great",
      "Option two can be something else and selecting it will deselect option one"] %>

  <%= f.input :terms %>

  <%= f.button :submit %>
<% end %>

app/views/results/_wrapper_mapping.html.erb
{ string: :string_wrapper, boolean: :boolean_wrapper }

app/views/results/index.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
  <li class="breadcrumb-item active">Results (show & export)</li>
<% end %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-10">See form results & export</h1>
    <ol>
      <li>Show form results <code>(Form A : Form B or Form C)</code></li>
      <li>Export results to <code>CSV</code> or <code>Excel</code></li>
    </ol>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <% if @patients.size == 0 %>
      <span class="label label-primary active">No patients recorded</span>
    <% else %>
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Patient ID</th>
            <th>Patient Name</th>
            <th>Form completed</th>
            <th colspan="2"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.id %></td>
              <td><%= patient.email %></td>
              <td>
                <% if patient.status == 1 %>
                  <span class="label label-primary active">YES</span>
                <% else %>
                  <span class="label label-success inactive">NO</span>
                <% end %>
              </td>
              <td><%= link_to "Show results", results_show_path(patient.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/results/show.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
  <li class="breadcrumb-item active">Results (show & export)
  &nbsp;
  <%= link_to "Download as CSV", results_export_path(format: "csv") %> |
  <%= link_to "Download as Excel", results_export_path(format: "xls") %></li>
<% end %>

<% if @answers.size > 0 %>
  <div class="container">
    <span class="label label-primary active">No forms submitted</span>
  </div>
<% else %>
  <div class="container">
  <h4 class="display-20">Form A</h4>
  <div class="row justify-content-center">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
    
      <tbody>
        <% @answers.where(:form_id => 1).each do |answer| %>
          <tr>
            <td><%= answer.question_text %></td>
            <td><%= answer.value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

  <div class="container">
  <h4 class="display-20">Form B</h4>
  <div class="row justify-content-center">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
    
      <tbody>
        <% @answers.where(:form_id => 2).each do |answer| %>
          <tr>
            <td><%= answer.question_text %></td>
            <td><%= answer.value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

  <div class="container">
  <h4 class="display-20">Form C</h4>
  <div class="row justify-content-center">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
    
      <tbody>
        <% @answers.where(:form_id => 3).each do |answer| %>
          <tr>
            <td><%= answer.question_text %></td>
            <td><%= answer.value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
<% end %> 