config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :lotteries

  get 'get_lotteries', to: 'lotteries#get_data', :as => 'get_lottery'

  resources :items
  resources :items_imports, only: [:new, :create]
  resources :archives, only: [:index, :new, :create, :destroy]


  devise_for :users

  get 'results'                     => 'results#index',   :as => 'results'
  get 'results/:patient_id'         => 'results#show',    :as => 'results_show'
  get 'results/:patient_id/export'  => 'results#export',  :as => 'results_export'

  resources :forms, only: [ :new, :create, :index, :show] do
    resources :questions, only: [:index, :show] do
      resources :answers
    end
  end

  namespace :api do
    namespace :v1 do
      get 'lotteries/:phone_number', to: 'api#lotteries_by_phone_number', :as => 'lotteries_by_phone_number'
    end
  end

end

app/models/lottery.rb
class Lottery < ApplicationRecord
end

app/controllers/lotteries_controller.rb
class LotteriesController < ApplicationController
  before_action :set_lottery, only: [:show, :edit, :update, :destroy]

  # GET /lotteries
  # GET /lotteries.json
  def index
    @lotteries = Lottery.all
  end

  def get_data 
    render json: { data: Lottery.all }
  end

  # GET /lotteries/1
  # GET /lotteries/1.json
  def show
  end

  def search
  end

  # GET /lotteries/new
  def new
    @lottery = Lottery.new
  end

  # GET /lotteries/1/edit
  def edit
  end

  # POST /lotteries
  # POST /lotteries.json
  def create
    @lottery = Lottery.new(lottery_params)

    respond_to do |format|
      if @lottery.save
        format.html { redirect_to @lottery, notice: 'Lottery was successfully created.' }
        format.json { render :show, status: :created, location: @lottery }
      else
        format.html { render :new }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lotteries/1
  # PATCH/PUT /lotteries/1.json
  def update
    respond_to do |format|
      if @lottery.update(lottery_params)
        format.html { redirect_to @lottery, notice: 'Lottery was successfully updated.' }
        format.json { render :show, status: :ok, location: @lottery }
      else
        format.html { render :edit }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotteries/1
  # DELETE /lotteries/1.json
  def destroy
    @lottery.destroy
    respond_to do |format|
      format.html { redirect_to lotteries_url, notice: 'Lottery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lottery
      @lottery = Lottery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lottery_params
      params.require(:lottery).permit(:phone_number, :lottery_number)
    end
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/views/lotteries/_form.html.erb
<%= simple_form_for(@lottery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :phone_number %>
    <%= f.input :lottery_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lotteries/edit.html.erb
<h1>Editing Lottery</h1>

<%= render 'form', lottery: @lottery %>

<%= link_to 'Show', @lottery %> |
<%= link_to 'Back', lotteries_path %>

app/views/lotteries/index.html.erb
<div class="container table-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table id="example" class="display">
      </table>
    </div>
  </div>
</div>

app/views/lotteries/new.html.erb
<h1>New Lottery</h1>

<%= render 'form', lottery: @lottery %>

<%= link_to 'Back', lotteries_path %>

app/views/lotteries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @lottery.phone_number %>
</p>

<p>
  <strong>Lottery number:</strong>
  <%= @lottery.lottery_number %>
</p>

<%= link_to 'Edit', edit_lottery_path(@lottery) %> |
<%= link_to 'Back', lotteries_path %>