config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :lotteries

  get 'get_lotteries', to: 'lotteries#get_data', :as => 'get_lottery'

  resources :items
  resources :items_imports, only: [:new, :create]
  resources :archives, only: [:index, :new, :create, :destroy]


  devise_for :users

  get 'results'                     => 'results#index',   :as => 'results'
  get 'results/:patient_id'         => 'results#show',    :as => 'results_show'
  get 'results/:patient_id/export'  => 'results#export',  :as => 'results_export'

  resources :forms, only: [ :new, :create, :index, :show] do
    resources :questions, only: [:index, :show] do
      resources :answers
    end
  end

  namespace :api do
    namespace :v1 do
      get 'lotteries/:phone_number', to: 'api#lotteries_by_phone_number', :as => 'lotteries_by_phone_number'
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  # validations
  validates_presence_of :user_id, :form_id, :question_id, :sub_question_id, :form_name, :question_text, :value

  def self.get_answers(user_id)
    Answer.where(user_id: user_id)
  end

  def self.get_answers_for_export(user_id)
    Answer.select("form_name, question_text, value").where(user_id: user_id)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |form|
        csv << form.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  mount_uploader :attachment, DocumentUploader
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
  include ActiveModel::Model
  require 'roo'

  attr_accessor :file

  def initialize(attributes={})
    attributes.each { |title, value| send("#{title}=", value) } unless attributes.nil?
  end

  def persisted?
    false
  end

  def open_spreadsheet
    case File.extname(file.path)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.path}"
    end
  end

  def load_imported_forms
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(5)
    (6..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      form = Form.find_by_id(row["id"]) || Form.new
      form.attributes = row.to_hash
      form
    end
  end

  def imported_forms
    @imported_forms ||= load_imported_forms
  end

  def save
    if imported_forms.map(&:valid?).all?
      imported_forms.each(&:save!)
      true
    else
      imported_forms.each_with_index do |form, index|
        form.errors.full_messages.each do |msg|
          errors.add :base, "Row #{index + 6}: #{msg}"
        end
      end
      false
    end
  end
  # model association
  # has_many :questions, dependent: :destroy

  # validations
  # validates_presence_of :title, :description
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :phone_number
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :attachment
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(attachment.original_filename)
      when ".xlsx" then Roo::Excelx.new('public/' + DocumentUploader.store_dir + '/' + attachment.original_filename)
      else raise "Unknown file type: #{attachment.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(2)
      (3..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by(phone_number: row["phone_number"], price_info: row["price_info"]) || Item.new
        if item.price_info != nil && row["price_info"].to_i >= 100000
          lottery_count = row["price_info"].to_i/100000
          string_arr = Lottery.pluck(:lottery_number)
          l_number_arr = string_arr.map(&:to_i)
          for lottery in 1..lottery_count
            lottery = Lottery.new do |l|
              l.phone_number = row["phone_number"]
              random_pick = ([*1..99999] - l_number_arr).sample
              l_number_arr.push(random_pick)              
              random_pick.to_s.rjust(5, "0")
              l.lottery_number = random_pick
            end
            lottery.save!
          end
        end
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/models/lottery.rb
class Lottery < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  # model association
  belongs_to :form

  # validations
  validates_presence_of :form_id, :sub_question_id, :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # role_id 0 = doctor, 1 = patients (default)
  def self.get_patients
    User.where(role_id: 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  # GET /forms
  def index
    #json_response(@forms)
  end

  # GET /forms/:id
  def show
    #json_response(@form)
  end 
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/icon_helper.rb
module IconHelper
  def icon_svg(path, html_options = {})
    content_tag :i, html_options.merge(class: "#{html_options[:class]} d-inline-block") do
      inline_svg path, class: "d-inline-block", width: "100%", height: "100%", preserve_aspect_ratio: "xMaxYMax meet"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def is_active?(link_path, return_class = "active")
    current_page?(link_path) ? return_class : nil
  end

  def markdown(source)
    options = {
      input: 'GFM',
      syntax_highlighter: :rouge,
      syntax_highlighter_opts: {
        css_class: 'highlight p-4 mb-0'
      }
    }
    Kramdown::Document.new(source, options).to_html.html_safe
  end

  def render_source(input, language = :erb, filename = nil)
    capture do
      concat content_tag(:p, "📂 #{filename}", class: "bg-light border small font-weight-bold px-4 py-2 mb-0 mt-4") if filename
      concat markdown("```#{language.to_s}\n#{input}```")
    end
  end
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/application/_breadcrumb.html.erb
<div class="app-breadcrumb container">
  <div class="d-flex flex-row justify-content-between">
    <ol class="breadcrumb bg-transparent px-0">
      <%= yield :breadcrumb %>
    </ol>

    <div>
      <button type="button" class="btn btn-sm btn-outline-secondary mt-2 mr-2 d-none" data-tooltip data-placement="bottom" data-trigger="hover" title="compare by clicking fast" data-toggle="button" aria-pressed="false" autocomplete="off">
        Swap
      </button>

      <div class="btn-group btn-group-toggle mt-2 d-none" data-toggle="buttons">
        <label class="btn btn-sm btn-outline-secondary">
          <input type="radio" name="view" id="stack" autocomplete="off"> Stack
        </label>
        <label class="btn btn-sm btn-outline-secondary active">
          <input type="radio" name="view" id="split" autocomplete="off" checked> Split
        </label>
      </div>
    </div>
  </div>
</div>

app/views/application/_flash.html.erb
<% if flash.any? %>
  <div class="app-flash">
    <% flash.each do |type, body| %>
      <%# only render the usual messages %>
      <% next unless %w(success notice error info).include?(type.to_s) %>

      <%= content_tag :div, class: "alert alert-#{type} alert-flash" do %>
        <div class="container">

          <div class="media">
            <%= icon_svg("alerts/#{type}.svg", class: "d-flex mr-3 icon icon-3x") %>
            <div class="media-body">
              <%= content_tag(:h6, t(".headline.#{type}"), class: "text-uppercase text-reset my-1") %>
              <% if body.kind_of?(Array) %>
                <ul class="mb-0">
                  <% body.each do |message| %>
                    <%= content_tag(:li, message) %>
                  <% end %>
                </ul>
              <% else %>
                <p class="mb-0"><%= body %></p>
              <% end %>
            </div>
          </div>

        </div>
      <% end if body.present? %>
    <% end %>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="app-footer text-center">
  <div class="container">
    <p>Copyright <%= Time.now.year %> Digital Assets Mongolia</p>
  </div>
</footer>

app/views/application/_header.html.erb
<div class="app-header">
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Lottery Submission Application", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
          <%= content_tag(:li, link_to("Lottery", lotteries_path, class: "nav-link"), class: "nav-item #{is_active?(lotteries_path)}") %>
          <% if user_signed_in? %>
            <%= content_tag(:li, link_to("Log out", destroy_user_session_path, method: :delete, class: "nav-link"), class: "nav-item #{is_active?(results_path)}") %>
          <% else %>
            <%= content_tag(:li, link_to("Login", new_user_session_path, class: "nav-link"), class: "nav-item #{is_active?(results_path)}") %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/application/_jumbotron.html.erb
<section class="app-jumbotron jumbotron text-center">
  <div class="container">
<h1 class="jumbotron-heading">Upload file</h1>
    <p class="lead text-muted">
      File must be in xlsx format
    </p>
    <p>
      <%= link_to 'Upload from Excel', new_form_path %> </br>
      <%= link_to "Results", results_path, class: "btn btn-secondary px-4 mx-2" %>
    </p>
</div>
</section>